# Generated by Django 2.1.7 on 2019-04-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_date', models.CharField(max_length=255)),
                ('data', models.ImageField(blank=True, upload_to='files/usr/data')),
            ],
        ),
    ]
