# Generated by Django 2.1.7 on 2019-04-16 13:48

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.ImageField(blank=True, null=True, upload_to=files.models.get_file_path, verbose_name='imgs'),
        ),
    ]
