# Generated by Django 2.1.7 on 2019-04-16 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20190416_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='upload_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
