<<<<<<< HEAD:notebook/upload_files/migrations/0001_initial.py
# Generated by Django 2.1.7 on 2019-04-23 05:51
=======
# Generated by Django 2.2 on 2019-04-29 03:37
>>>>>>> 78be7dce9ecf9030ee273782dba51f48992a09eb:notebook/ML/migrations/0001_initial.py

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20190416_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD:notebook/upload_files/migrations/0001_initial.py
                ('url', models.ImageField(upload_to=upload_files.models.user_path)),
=======
                ('url', models.CharField(max_length=255)),
>>>>>>> 78be7dce9ecf9030ee273782dba51f48992a09eb:notebook/ML/migrations/0001_initial.py
                ('texts', jsonfield.fields.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('publish', models.BooleanField(default=False)),
                ('member_idx', models.ForeignKey(db_column='member_idx', on_delete=django.db.models.deletion.CASCADE, to='login.Member')),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
