# Generated by Django 2.2 on 2019-04-29 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='member_idx',
            field=models.ForeignKey(db_column='member_idxdddd', on_delete=django.db.models.deletion.CASCADE, to='login.Member'),
        ),
    ]
