# Generated by Django 2.2 on 2019-04-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0002_auto_20190429_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='member_idx',
            field=models.ForeignKey(db_column='member_idx', on_delete=django.db.models.deletion.CASCADE, to='login.Member'),
        ),
    ]
