# Generated by Django 2.2 on 2019-04-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0004_auto_20190430_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='image_path',
            new_name='url',
        ),
    ]
