# Generated by Django 2.2 on 2019-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0005_auto_20190430_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='member_fake',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
