# Generated by Django 2.2 on 2019-05-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0007_remove_data_member_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='model',
            field=models.CharField(default='simple', max_length=255),
            preserve_default=False,
        ),
    ]
