# Generated by Django 2.1.7 on 2019-04-17 02:50

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import upload_files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20190416_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.ImageField(upload_to=upload_files.models.get_file_path, verbose_name='imgs')),
                ('texts', jsonfield.fields.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('publish', models.BooleanField(null=True)),
                ('member_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_idx', to='login.Member')),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
