# Generated by Django 2.1.7 on 2019-04-17 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0002_auto_20190417_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='member_idx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m', to='login.Member'),
        ),
    ]
