# Generated by Django 2.1.7 on 2019-04-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0003_auto_20190417_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='member_idx',
            field=models.ForeignKey(db_column='member_idx', on_delete=django.db.models.deletion.CASCADE, to='login.Member'),
        ),
        migrations.AlterField(
            model_name='data',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
